<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ManagedBass" Version="3.1.1" />
	</ItemGroup>
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x86'OR ('$(Configuration)' == 'Debug' AND '$(Platform)' == 'AnyCPU' AND '$(PROCESSOR_ARCHITECTURE)' == 'x86')">
		<None Update="BASS\win-x86\bass.dll">
			<TargetPath>bass.dll</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' OR ('$(Configuration)' == 'Debug' AND '$(Platform)' == 'AnyCPU' AND '$(PROCESSOR_ARCHITECTURE)' == 'AMD64')">
		<None Update="BASS\win-x64\bass.dll">
			<TargetPath>bass.dll</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
		<None Update="BASS\osx-arm64\libbass.dylib">
			<TargetPath>libbass.dylib</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
		<None Update="BASS\linux-arm64\libbass.so">
			<TargetPath>libbass.so</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
		<None Update="BASS\linux-x64\libbass.so">
			<TargetPath>libbass.so</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="Minigames\PlatformerMap1.bmp">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Minigames\PlatformerMap2.bmp">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Minigames\PlatformerMap3.bmp">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Acoustic Optimistic.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Climb Together Ending.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Desert.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Kool Kats.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Now.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Sneaky Snitch.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\Spear Of Justice.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Music\The Complex.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Bleep.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\BlockBreak.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Chahoo.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\CheeringOn.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\DamageTaken.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Death.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Ding.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Fall1.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Fall2.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Fall3.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\FireWoosh.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Lose.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Miss.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Nice1.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Nice2.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Nice3.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Nice4.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Ouch1.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Ouch2.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Ouch3.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Strike.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\SwimmingPool.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\TooSlow.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Whistle.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\Win.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="SFX\WinRace.mp3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
